spring:
  application:
    #  projectName
    name: WxOnlineExam
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/questions?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
server:
  port: 8081
  #  Uniform request prefix
  servlet:
      context-path: /question

# Automatic hump switching is prohibited
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  # Automatically skip data that has been logically deleted
  global-config:
    db-config:
      logic-delete-field: isDelete # Entity field name for global logical deletion (since 3.3.0, step 2 can be ignored after configuration)
      logic-delete-value: 1 # Logical deleted value (default is 1)
      logic-not-delete-value: 0 # Logical undeleted value (default is 0)
